package com.sofa.mapper;

import com.sofa.model.EnshrineInfo;
import com.sofa.model.EnshrineInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnshrineInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_enshrine_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int countByExample(EnshrineInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_enshrine_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int deleteByExample(EnshrineInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_enshrine_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_enshrine_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int insert(EnshrineInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_enshrine_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int insertSelective(EnshrineInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_enshrine_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    List<EnshrineInfo> selectByExample(EnshrineInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_enshrine_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    EnshrineInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_enshrine_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") EnshrineInfo record, @Param("example") EnshrineInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_enshrine_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByExample(@Param("record") EnshrineInfo record, @Param("example") EnshrineInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_enshrine_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByPrimaryKeySelective(EnshrineInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_enshrine_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByPrimaryKey(EnshrineInfo record);
}