package com.sofa.mapper;

import com.sofa.model.JourneyCommentInfo;
import com.sofa.model.JourneyCommentInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JourneyCommentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_comment_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int countByExample(JourneyCommentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_comment_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int deleteByExample(JourneyCommentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_comment_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_comment_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int insert(JourneyCommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_comment_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int insertSelective(JourneyCommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_comment_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    List<JourneyCommentInfo> selectByExample(JourneyCommentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_comment_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    JourneyCommentInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_comment_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") JourneyCommentInfo record, @Param("example") JourneyCommentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_comment_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByExample(@Param("record") JourneyCommentInfo record, @Param("example") JourneyCommentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_comment_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByPrimaryKeySelective(JourneyCommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_comment_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByPrimaryKey(JourneyCommentInfo record);
}