package com.sofa.mapper;

import com.sofa.model.JourneyUserInfo;
import com.sofa.model.JourneyUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JourneyUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_user_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int countByExample(JourneyUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_user_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int deleteByExample(JourneyUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_user_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_user_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int insert(JourneyUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_user_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int insertSelective(JourneyUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_user_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    List<JourneyUserInfo> selectByExample(JourneyUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_user_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    JourneyUserInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_user_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") JourneyUserInfo record, @Param("example") JourneyUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_user_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByExample(@Param("record") JourneyUserInfo record, @Param("example") JourneyUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_user_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByPrimaryKeySelective(JourneyUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_user_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByPrimaryKey(JourneyUserInfo record);
}