package com.sofa.mapper;

import com.sofa.model.JourneyStarInfo;
import com.sofa.model.JourneyStarInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JourneyStarInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_star_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int countByExample(JourneyStarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_star_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int deleteByExample(JourneyStarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_star_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_star_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int insert(JourneyStarInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_star_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int insertSelective(JourneyStarInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_star_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    List<JourneyStarInfo> selectByExample(JourneyStarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_star_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    JourneyStarInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_star_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") JourneyStarInfo record, @Param("example") JourneyStarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_star_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByExample(@Param("record") JourneyStarInfo record, @Param("example") JourneyStarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_star_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByPrimaryKeySelective(JourneyStarInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey_star_info
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    int updateByPrimaryKey(JourneyStarInfo record);
}