package com.sofa.model;

public class CityInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_city_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_city_info.city_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_city_info.city_code
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_city_info.province_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_city_info.province_code
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_city_info.state_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String stateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_city_info.state_code
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer stateCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_city_info.id
     *
     * @return the value of common_city_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_city_info.id
     *
     * @param id the value for common_city_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_city_info.city_name
     *
     * @return the value of common_city_info.city_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_city_info.city_name
     *
     * @param cityName the value for common_city_info.city_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_city_info.city_code
     *
     * @return the value of common_city_info.city_code
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_city_info.city_code
     *
     * @param cityCode the value for common_city_info.city_code
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_city_info.province_name
     *
     * @return the value of common_city_info.province_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_city_info.province_name
     *
     * @param provinceName the value for common_city_info.province_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_city_info.province_code
     *
     * @return the value of common_city_info.province_code
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_city_info.province_code
     *
     * @param provinceCode the value for common_city_info.province_code
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setProvinceCode(Integer provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_city_info.state_name
     *
     * @return the value of common_city_info.state_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getStateName() {
        return stateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_city_info.state_name
     *
     * @param stateName the value for common_city_info.state_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setStateName(String stateName) {
        this.stateName = stateName == null ? null : stateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_city_info.state_code
     *
     * @return the value of common_city_info.state_code
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getStateCode() {
        return stateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_city_info.state_code
     *
     * @param stateCode the value for common_city_info.state_code
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setStateCode(Integer stateCode) {
        this.stateCode = stateCode;
    }
}