package com.sofa.model;

import java.util.Date;

public class CommonAccusationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_accusation_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_accusation_info.user_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_accusation_info.accusated_user_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer accusatedUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_accusation_info.accusation_type
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer accusationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_accusation_info.accusation_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Date accusationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_accusation_info.id
     *
     * @return the value of common_accusation_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_accusation_info.id
     *
     * @param id the value for common_accusation_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_accusation_info.user_id
     *
     * @return the value of common_accusation_info.user_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_accusation_info.user_id
     *
     * @param userId the value for common_accusation_info.user_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_accusation_info.accusated_user_id
     *
     * @return the value of common_accusation_info.accusated_user_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getAccusatedUserId() {
        return accusatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_accusation_info.accusated_user_id
     *
     * @param accusatedUserId the value for common_accusation_info.accusated_user_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setAccusatedUserId(Integer accusatedUserId) {
        this.accusatedUserId = accusatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_accusation_info.accusation_type
     *
     * @return the value of common_accusation_info.accusation_type
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getAccusationType() {
        return accusationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_accusation_info.accusation_type
     *
     * @param accusationType the value for common_accusation_info.accusation_type
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setAccusationType(Integer accusationType) {
        this.accusationType = accusationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_accusation_info.accusation_time
     *
     * @return the value of common_accusation_info.accusation_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Date getAccusationTime() {
        return accusationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_accusation_info.accusation_time
     *
     * @param accusationTime the value for common_accusation_info.accusation_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setAccusationTime(Date accusationTime) {
        this.accusationTime = accusationTime;
    }
}