package com.sofa.model;

import java.util.Date;

public class EnshrineInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_enshrine_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_enshrine_info.user_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_enshrine_info.resource_main_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer resourceMainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_enshrine_info.add_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_enshrine_info.id
     *
     * @return the value of common_enshrine_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_enshrine_info.id
     *
     * @param id the value for common_enshrine_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_enshrine_info.user_id
     *
     * @return the value of common_enshrine_info.user_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_enshrine_info.user_id
     *
     * @param userId the value for common_enshrine_info.user_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_enshrine_info.resource_main_id
     *
     * @return the value of common_enshrine_info.resource_main_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getResourceMainId() {
        return resourceMainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_enshrine_info.resource_main_id
     *
     * @param resourceMainId the value for common_enshrine_info.resource_main_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setResourceMainId(Integer resourceMainId) {
        this.resourceMainId = resourceMainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_enshrine_info.add_time
     *
     * @return the value of common_enshrine_info.add_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_enshrine_info.add_time
     *
     * @param addTime the value for common_enshrine_info.add_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}