package com.sofa.model;

public class JourneyStarInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_star_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_star_info.journey_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String journeyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_star_info.user_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_star_info.id
     *
     * @return the value of journey_star_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_star_info.id
     *
     * @param id the value for journey_star_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_star_info.journey_id
     *
     * @return the value of journey_star_info.journey_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getJourneyId() {
        return journeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_star_info.journey_id
     *
     * @param journeyId the value for journey_star_info.journey_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setJourneyId(String journeyId) {
        this.journeyId = journeyId == null ? null : journeyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_star_info.user_id
     *
     * @return the value of journey_star_info.user_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_star_info.user_id
     *
     * @param userId the value for journey_star_info.user_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}