package com.sofa.model;

import java.util.Date;

public class JourneyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.start_date
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.end_date
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.launch_user
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String launchUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.start_city
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer startCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.destination_city
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer destinationCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.title
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.content
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.location_latitude
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String locationLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.location_longtitude
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String locationLongtitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.images
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.add_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.del_flag
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey_info.icon_url
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String iconUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.id
     *
     * @return the value of journey_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.id
     *
     * @param id the value for journey_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.start_date
     *
     * @return the value of journey_info.start_date
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.start_date
     *
     * @param startDate the value for journey_info.start_date
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.end_date
     *
     * @return the value of journey_info.end_date
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.end_date
     *
     * @param endDate the value for journey_info.end_date
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.launch_user
     *
     * @return the value of journey_info.launch_user
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getLaunchUser() {
        return launchUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.launch_user
     *
     * @param launchUser the value for journey_info.launch_user
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setLaunchUser(String launchUser) {
        this.launchUser = launchUser == null ? null : launchUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.start_city
     *
     * @return the value of journey_info.start_city
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.start_city
     *
     * @param startCity the value for journey_info.start_city
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setStartCity(Integer startCity) {
        this.startCity = startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.destination_city
     *
     * @return the value of journey_info.destination_city
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getDestinationCity() {
        return destinationCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.destination_city
     *
     * @param destinationCity the value for journey_info.destination_city
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setDestinationCity(Integer destinationCity) {
        this.destinationCity = destinationCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.title
     *
     * @return the value of journey_info.title
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.title
     *
     * @param title the value for journey_info.title
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.content
     *
     * @return the value of journey_info.content
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.content
     *
     * @param content the value for journey_info.content
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.location_latitude
     *
     * @return the value of journey_info.location_latitude
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getLocationLatitude() {
        return locationLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.location_latitude
     *
     * @param locationLatitude the value for journey_info.location_latitude
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setLocationLatitude(String locationLatitude) {
        this.locationLatitude = locationLatitude == null ? null : locationLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.location_longtitude
     *
     * @return the value of journey_info.location_longtitude
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getLocationLongtitude() {
        return locationLongtitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.location_longtitude
     *
     * @param locationLongtitude the value for journey_info.location_longtitude
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setLocationLongtitude(String locationLongtitude) {
        this.locationLongtitude = locationLongtitude == null ? null : locationLongtitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.images
     *
     * @return the value of journey_info.images
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.images
     *
     * @param images the value for journey_info.images
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.add_time
     *
     * @return the value of journey_info.add_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.add_time
     *
     * @param addTime the value for journey_info.add_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.del_flag
     *
     * @return the value of journey_info.del_flag
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.del_flag
     *
     * @param delFlag the value for journey_info.del_flag
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey_info.icon_url
     *
     * @return the value of journey_info.icon_url
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey_info.icon_url
     *
     * @param iconUrl the value for journey_info.icon_url
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }
}