package com.sofa.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.real_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nick_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mobile
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.identity_flag
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer identityFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.identity_type
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer identityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.identity_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String identityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birthday
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.age
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sex
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.first_language
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String firstLanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.second_language
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String secondLanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.job
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.school
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.city_code
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.interests
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String interests;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.head_image
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String headImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.introduction
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.default_role
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer defaultRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.state
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.del_flag
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_logintime
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Date lastLogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.add_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.location_latitude
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String locationLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.location_longtitude
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    private String locationLongtitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.real_name
     *
     * @return the value of user_info.real_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.real_name
     *
     * @param realName the value for user_info.real_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nick_name
     *
     * @return the value of user_info.nick_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nick_name
     *
     * @param nickName the value for user_info.nick_name
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mobile
     *
     * @return the value of user_info.mobile
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mobile
     *
     * @param mobile the value for user_info.mobile
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.identity_flag
     *
     * @return the value of user_info.identity_flag
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getIdentityFlag() {
        return identityFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.identity_flag
     *
     * @param identityFlag the value for user_info.identity_flag
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setIdentityFlag(Integer identityFlag) {
        this.identityFlag = identityFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.identity_type
     *
     * @return the value of user_info.identity_type
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getIdentityType() {
        return identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.identity_type
     *
     * @param identityType the value for user_info.identity_type
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setIdentityType(Integer identityType) {
        this.identityType = identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.identity_id
     *
     * @return the value of user_info.identity_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.identity_id
     *
     * @param identityId the value for user_info.identity_id
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setIdentityId(String identityId) {
        this.identityId = identityId == null ? null : identityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birthday
     *
     * @return the value of user_info.birthday
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birthday
     *
     * @param birthday the value for user_info.birthday
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.age
     *
     * @return the value of user_info.age
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.age
     *
     * @param age the value for user_info.age
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sex
     *
     * @return the value of user_info.sex
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sex
     *
     * @param sex the value for user_info.sex
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.first_language
     *
     * @return the value of user_info.first_language
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getFirstLanguage() {
        return firstLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.first_language
     *
     * @param firstLanguage the value for user_info.first_language
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setFirstLanguage(String firstLanguage) {
        this.firstLanguage = firstLanguage == null ? null : firstLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.second_language
     *
     * @return the value of user_info.second_language
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getSecondLanguage() {
        return secondLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.second_language
     *
     * @param secondLanguage the value for user_info.second_language
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setSecondLanguage(String secondLanguage) {
        this.secondLanguage = secondLanguage == null ? null : secondLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.job
     *
     * @return the value of user_info.job
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.job
     *
     * @param job the value for user_info.job
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.school
     *
     * @return the value of user_info.school
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.school
     *
     * @param school the value for user_info.school
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.city_code
     *
     * @return the value of user_info.city_code
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.city_code
     *
     * @param cityCode the value for user_info.city_code
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.interests
     *
     * @return the value of user_info.interests
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getInterests() {
        return interests;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.interests
     *
     * @param interests the value for user_info.interests
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setInterests(String interests) {
        this.interests = interests == null ? null : interests.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.head_image
     *
     * @return the value of user_info.head_image
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getHeadImage() {
        return headImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.head_image
     *
     * @param headImage the value for user_info.head_image
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setHeadImage(String headImage) {
        this.headImage = headImage == null ? null : headImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.introduction
     *
     * @return the value of user_info.introduction
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.introduction
     *
     * @param introduction the value for user_info.introduction
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.default_role
     *
     * @return the value of user_info.default_role
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getDefaultRole() {
        return defaultRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.default_role
     *
     * @param defaultRole the value for user_info.default_role
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setDefaultRole(Integer defaultRole) {
        this.defaultRole = defaultRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.state
     *
     * @return the value of user_info.state
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.state
     *
     * @param state the value for user_info.state
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.del_flag
     *
     * @return the value of user_info.del_flag
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.del_flag
     *
     * @param delFlag the value for user_info.del_flag
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_logintime
     *
     * @return the value of user_info.last_logintime
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Date getLastLogintime() {
        return lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_logintime
     *
     * @param lastLogintime the value for user_info.last_logintime
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setLastLogintime(Date lastLogintime) {
        this.lastLogintime = lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.add_time
     *
     * @return the value of user_info.add_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.add_time
     *
     * @param addTime the value for user_info.add_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.location_latitude
     *
     * @return the value of user_info.location_latitude
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getLocationLatitude() {
        return locationLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.location_latitude
     *
     * @param locationLatitude the value for user_info.location_latitude
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setLocationLatitude(String locationLatitude) {
        this.locationLatitude = locationLatitude == null ? null : locationLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.location_longtitude
     *
     * @return the value of user_info.location_longtitude
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public String getLocationLongtitude() {
        return locationLongtitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.location_longtitude
     *
     * @param locationLongtitude the value for user_info.location_longtitude
     *
     * @mbggenerated Wed Mar 14 10:41:03 CST 2018
     */
    public void setLocationLongtitude(String locationLongtitude) {
        this.locationLongtitude = locationLongtitude == null ? null : locationLongtitude.trim();
    }
}